database: "archive/cardio_train.csv"
result_location: "results/"
outlier_detection_technique: "combo"
machine_learning_model: 'linear_regression'
automate_feature_selection: false
expand_data_multiplier: 0
expanded_file_name: null
full_accuracy: false
planned_clusters: 2

runtime_parameters:
    choice_1:
        predictor: weight
        clustering: unsupervised
        cluster_alg: Minhal
        accuracy: 1
        split_size: 4
        preprocess_data: false
        postprocess_data: true
        batch_size: "1MB"
        batch_method: tree_index
    choice_2:
        predictor: weight
        clustering: unsupervised
        cluster_alg: Minhal
        accuracy: 1
        split_size: 4
        preprocess_data: false
        postprocess_data: true
        batch_size: "1MB"
        batch_method: binary_search
    choice_0:
        predictor: weight
        clustering: unsupervised
        cluster_alg: Minhal
        accuracy: 1
        split_size: 4
        preprocess_data: false
        postprocess_data: true
        batch_size: "1MB"
        batch_method: array_index