# Path to database used
database: archive/sntemp_inputs_outputs_lordville.csv

result_location: "results/"

# Outlier detection options: 'z_score', 'i_forest', 'combo'
outlier_detection_technique: "combo"

# Machine learning options: 'lstm' or 'linear_regression'
machine_learning_model: "linear_regression"

# A placeholder for now that will should remain False until someone implements a feature that allows
# the program to decide which features should be used to predict other features.
automate_feature_selection: false
use_one_predictor: false

# If you wish to expand data set this variable to a whole number greater than 1. The dataset will be expanded
# by that multiplier with noise being added to continuous columns (as defined in datasets_info.yaml)
expand_data_multiplier: 0

# Path and file name used to store expanded file. If multiplier is set to 1, this is ignored.
# If expanded file name is null it will not save the expanded database. Saving expanded databse
# could be useful for reproducibility purposes or for speed.
expanded_file_name: null

# Will run special test that prints creates graph comparing trade off between accuracy and number of outliers
full_accuracy: false

# Allows you to select how many cluster will be created by the clustering algorithms listed below
planned_clusters: 2

runtime_parameters:
  choice_1:
    predictor: Index
    clustering: unsupervised
    cluster_alg: Minhal # KM, Dist, Minhal, Bisect, Birch
    accuracy: 1
    split_size: 3
    preprocess_data: false
    postprocess_data: true
    batch_size:
  choice_2:
    predictor: Index
    clustering: unsupervised
    cluster_alg: Minhal # KM, Dist, Minhal, Bisect, Birch
    accuracy: 2.5
    split_size: 3
    preprocess_data: false
    postprocess_data: true
    batch_size:
  choice_3:
    predictor: Index
    clustering: unsupervised
    cluster_alg: Minhal # KM, Dist, Minhal, Bisect, Birch
    accuracy: 5
    split_size: 3
    preprocess_data: false
    postprocess_data: true
    batch_size:
  choice_4:
    predictor: Index
    clustering: unsupervised
    cluster_alg: Minhal # KM, Dist, Minhal, Bisect, Birch
    accuracy: .5
    split_size: 3
    preprocess_data: false
    postprocess_data: true
    batch_size:
  choice_5:
    predictor: Index
    clustering: unsupervised
    cluster_alg: Minhal # KM, Dist, Minhal, Bisect, Birch
    accuracy: .25
    split_size: 3
    preprocess_data: false
    postprocess_data: true
    batch_size:

# Specifies which features are used to predictors for other features
# If automate_feature_selection is set to true, this section will be ignored
predictors:
  attr5:
    - "attr0"
